openapi: 3.0.1
info:
  title: DynamicAPI
  description: API Definition of DynamicAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/dynamicAPI
paths:
  /:
    post:
      responses:
        default:
          description: Default response
